# Travis CI configuration file for running tests
sudo: false
language: python
branches:
    only:
      - master
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt
script:
  - pep8 .
  - coverage run --source=edx_sitespeed -m nose
after_success:
  - pip install coveralls
  - coveralls
